LESSON 3

Create a program that determines and displays the number of unique characters in a string entered by the user. For example, "Hello, World!" has 10 unique characters while "zzz" has only one unique character. Use a dictionary or set to solve this problem.

In [18]:
string=input("Give a string, please: ")
no_repetition=set(string)
result=len(no_repetition)
print(f"Your string {string} has {result} unique characters")

Give a string, please: kell
Your string kell has 3 unique characters


 Pig Latin is a language constructed by transforming English words. While the origins of the language are unknown, it is mentioned in at least two documents from the nineteenth century, suggesting that it has existed for more than 100 years. The following rules are used to translate English into Pig Latin:

If the word begins with a consonant (including y), then all letters at the beginning of the word, up to the first vowel (excluding y), are removed and then added to the end of the word, followed by ay. For example, computer becomes omputercay and think becomes inkthay.
If the word begins with a vowel (not including y), then way is added to the end of the word. For example, algorithm becomes algorithmway and office becomes officeway.
Write a program that reads a line of text from the user. Then your program should translate the line into Pig Latin and display the result. You may assume that the string entered by the user only contains lowercase letters and spaces.

In [98]:
string=input()
vowels="aeiou"
words=string.split(" ") 
final=""
count=0
for word in words:
    if word[0] in vowels:
        final+=word
        final+="way "
        
    else: 
        word=word[1:]+word[0]
        final+=word
        final+="ay "
    
print(final)
        

how are you today
owhay areway ouyay odaytay 


Create a class that checks the authorization. Its constructor takes correct user name and password and store them as attributes. To increase security the password must not be stored as it is. Convert it to hash using function hash(). Also the class has a method check that accepts a user name and password input by a user and return True if they are correct and False otherwise. Write a program that demonstrates how this class works.

In [151]:
class Initialization():
    def __init__(self, name, password):
        self.name=name
        self.password=password
        print("Admin is created")
    def check(self):
        a=input("Please, enter your name: ")
        b=hash(input("Please,enter password:"))
        if a==self.name and b==self.password:
            return True
        else:
            return False
admin=Initialization("Maya", hash("beca7us123"))
print(admin.password)
admin.check()


        
        

Admin is created
45567438901932510
Please, enter your name: Maya
Please,enter password:bea443


False

LESSON 4

Write a program that creates a NumPy array containing 20 zeros, then reshape it to get a two-dimensional array with 5 rows and 4 columns. Print this array. Now assign to its middle area 1 to obtain an array whose the first and the last rows as well as the first and the last columns contain 0 and all others are 1. Print this array.

In [276]:
import numpy as np 
c = np.zeros(20)
b=c.reshape(5,4)
b[1:4,1:3]=1
print(b)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [277]:
file_name = "presidents.csv"

txt = ['Garfield, 183', 'Obama, 185', 'Bush, 182', 'Reagan, 185', 'Kennedy, 185', 'Grant, 173', 'Taft, 182', 'Johnson, 192', 'Coolidge, 178', 'Arthur, 188', 'Bush, 188', 'Wilson, 180', 'Monroe, 183', 'Buchanan, 183', 'Roosevelt, 188', 'Johnson, 178', 'Cleveland, 180', 'Jackson, 185', 'McKinley, 170', 'Harrison, 168', 'Polk, 173', 'Taylor, 173', 'Truman, 175', 'Harding, 183', 'Buren, 168', 'Ford, 183', 'Clinton, 188', 'Carter, 177', 'Q_Adams, 171', 'Trump, 191', 'Jefferson, 189', 'Nixon, 182', 'Pierce, 178', 'Washington, 188', 'Lincoln, 193', 'Madison, 163', 'Hoover, 182', 'Roosevelt, 178', 'Adams, 170', 'Tyler, 183', 'Fillmore, 175', 'Harrison, 173', 'Hayes, 174', 'Eisenhower, 179']
with open(file_name, "w") as f:
    for s in txt:
        f.write(s + '\n')

Create a program that reads president heights form a file presidents.csv and store them into a NumPy array. Execute the section above to get this file in your working directory. Read only heights, without names. Then compute and print the smallest, the biggest and the mean height.
I MADE TWO WAYS OF SOLVING



In [382]:
file_name = "presidents.csv"

with open(file_name, 'r') as f:
    dat = []
    for line in f:
        s = line.split(',')
        s = [c.strip() for c in s]
        dat.append(s[1])
print(dat)
max_height=max(dat)
min_height=min(dat)
count=len(dat)
s=map(int,dat)
summ=sum(s)
average_height=int(summ/count)
print(f"Максимальный рост равен {max_height}, минимальный рост равен {min_height}, средний рост равен {average_height}")

['183', '185', '182', '185', '185', '173', '182', '192', '178', '188', '188', '180', '183', '183', '188', '178', '180', '185', '170', '168', '173', '173', '175', '183', '168', '183', '188', '177', '171', '191', '189', '182', '178', '188', '193', '163', '182', '178', '170', '183', '175', '173', '174', '179']
Максимальный рост равен 193, минимальный рост равен 163, средний рост равен 180


In [381]:
import numpy as np
from numpy import genfromtxt
file_name = "presidents.csv"
count=0
my_data = genfromtxt('presidents.csv', delimiter=',')
heights=my_data[:,1]
print(heights)
summ=heights.sum()
amount=len(heights)
average_height=int(summ/amount)
max_height=int(heights.max())
min_height=int(heights.min())
print(f"Максимальный рост равен {max_height}, минимальный рост равен {min_height}, средний рост равен {average_height}")

[183. 185. 182. 185. 185. 173. 182. 192. 178. 188. 188. 180. 183. 183.
 188. 178. 180. 185. 170. 168. 173. 173. 175. 183. 168. 183. 188. 177.
 171. 191. 189. 182. 178. 188. 193. 163. 182. 178. 170. 183. 175. 173.
 174. 179.]
Максимальный рост равен 193, минимальный рост равен 163, средний рост равен 180


First run the above section to get a file "sleep.csv". This file contains three columns: sex, country and sleeping time. Create a program that reads this file converting the sleeping time from 'hh:mm' format to an integer numbers of minutes. Now print the answers to the following questions: What are the largest and the smallest sleeping time for males and females? In which country people sleep more? What is the average sleeping time?

In [383]:
# Run this section to get a file with sleep time
file_name = "sleep.csv"

txt = ["Males, Belgium, 8:15","Males, Bulgaria, 9:08","Males, Germany, 8:08","Males, Estonia, 8:24","Males, Spain, 8:36","Males, France, 8:45","Males, Italy, 8:17","Males, Latvia, 8:35","Males, Lithuania, 8:28","Males, Poland, 8:21","Males, Slovenia, 8:18","Males, Finland, 8:22","Males, United Kingdom, 8:18","Males, Norway, 7:56","Females, Belgium, 8:34","Females, Bulgaria, 9:07","Females, Germany, 8:15","Females, Estonia, 8:26","Females, Spain, 8:32","Females, France, 8:55","Females, Italy, 8:19","Females, Latvia, 8:44","Females, Lithuania, 8:35","Females, Poland, 8:35","Females, Slovenia, 8:25","Females, Finland, 8:32","Females, United Kingdom, 8:27","Females, Norway, 8:10"]
with open(file_name, "w") as f:
    for s in txt:
        f.write(s + '\n')


In [450]:
#Converting given time to minutes and finding max and min time of sleep for fem and male
def convert_to_minutes(array,gender):
    s=[]
    for i in array:
        input_time=i
        t=input_time.split(':')
        total_minutes= int(t[0])*60+int(t[1])*1
        s.append(total_minutes)
    max_time=max(s)
    min_time=min(s)
    print(f"The largest time for {gender} is {max_time} minutes and the smallest time is {min_time} minutes")

#Converting to minutes for average amount of time
def without_gender(j):
        input_time=j
        t=input_time.split(':')
        total_minutes= int(t[0])*60+int(t[1])*1
        return total_minutes
    
#body
import numpy as np
file_name = "sleep.csv"
#creating lists of male and female time of sleep and common list
with open(file_name, 'r') as f:
    dat=[]
    dat_male = []
    dat_fem=[]
    countries=[]
    time=[]
    for line in f:
        s = line.split(',')
        s = [c.strip() for c in s]
        dat.append(s[2])
        countries.append(s[1])
        if s[0]=="Males":
            dat_male.append(s[2])
        else:
            dat_fem.append(s[2])
#converting to minutes time in 'gender' lists
convert_to_minutes(dat_male,"male")
convert_to_minutes(dat_fem, "female")

#finding country where people sleep more 
for i,j in enumerate(time):
    if j==max(time):
        print("People sleep more in", countries[i])  

#finding average time of sleep
for i in dat:
    a=without_gender(i)
    time.append(a)
summ=sum(time)
average_time=int(summ/len(time))
print(f"Average time of sleep is {average_time} minutes")
    

The largest time for male is 548 minutes and the smallest time is 476 minutes
The largest time for female is 547 minutes and the smallest time is 490 minutes
Average time of sleep is 508 minutes
